name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Run Test
        run: |
          go test -v -cover ./... -coverprofile coverage.out -coverpkg ./...
          go tool cover -func coverage.out -o coverage.out

      - name: Go Coverage Badge
        uses: tj-actions/coverage-badge-go@v1
        with:
          green: 60
          filename: coverage.out
